#!/usr/bin/env python3
"""
Setup reverse proxy — generates nginx config for dual-port Render deploy.

Render exposes a single port. This script generates an nginx.conf that
routes mind-protocol API routes to the home_server (:8765) and everything
else to the org's frontend/backend (:10001).

Called by `mind init` and by the entrypoint at deploy time.

Usage:
    python scripts/setup_reverse_proxy.py [--port 10000] [--frontend-port 10001] [--backend-port 8765]

Generates:
    .mind/runtime/nginx.conf
    .mind/runtime/start.sh (supervisor script)
"""

import argparse
import os
import stat
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent


def generate_nginx_conf(
    listen_port: int = 10000,
    frontend_port: int = 10001,
    backend_port: int = 8765,
) -> str:
    """Generate nginx.conf for dual-port routing."""
    return f"""# Auto-generated by mind-mcp/scripts/setup_reverse_proxy.py
# Routes mind-protocol API to home_server, everything else to frontend

worker_processes 1;
daemon off;

events {{
    worker_connections 1024;
}}

http {{
    access_log /dev/stdout;
    error_log /dev/stderr;

    upstream home_server {{
        server 127.0.0.1:{backend_port};
    }}

    upstream frontend {{
        server 127.0.0.1:{frontend_port};
    }}

    server {{
        listen {listen_port};

        # Mind Protocol API routes → home_server
        location /membrane/ {{
            proxy_pass http://home_server;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }}

        location /ping/ {{
            proxy_pass http://home_server;
            proxy_set_header Host $host;
        }}

        location /health {{
            proxy_pass http://home_server;
        }}

        location /api/ {{
            proxy_pass http://home_server;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }}

        location /l4/ {{
            proxy_pass http://home_server;
            proxy_set_header Host $host;
        }}

        location /auth/ {{
            proxy_pass http://home_server;
            proxy_set_header Host $host;
        }}

        location /chat/ {{
            proxy_pass http://home_server;
            proxy_set_header Host $host;
        }}

        location /dm/ {{
            proxy_pass http://home_server;
            proxy_set_header Host $host;
        }}

        location /feed/ {{
            proxy_pass http://home_server;
            proxy_set_header Host $host;
        }}

        location /house/ {{
            proxy_pass http://home_server;
            proxy_set_header Host $host;
        }}

        location /whatsapp/ {{
            proxy_pass http://home_server;
            proxy_set_header Host $host;
        }}

        # WebSocket for voice
        location /voice/ws {{
            proxy_pass http://home_server;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }}

        # Everything else → frontend (Node/Python org server)
        location / {{
            proxy_pass http://frontend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }}
    }}
}}
"""


def generate_start_script(
    frontend_cmd: str,
    listen_port: int = 10000,
    frontend_port: int = 10001,
    backend_port: int = 8765,
) -> str:
    """Generate start.sh that launches all 3 processes."""
    return f"""#!/bin/bash
# Auto-generated by mind-mcp/scripts/setup_reverse_proxy.py
# Launches: nginx (:{listen_port}) + home_server (:{backend_port}) + frontend (:{frontend_port})

set -e

NGINX_CONF="$(dirname "$0")/nginx.conf"

echo "[start] Launching home_server on :{backend_port}..."
PORT={backend_port} python3 -m uvicorn home_server:app --host 0.0.0.0 --port {backend_port} --log-level info &
HOME_PID=$!

echo "[start] Launching frontend on :{frontend_port}..."
PORT={frontend_port} {frontend_cmd} &
FRONTEND_PID=$!

# Wait for both backends to be ready
sleep 2

echo "[start] Launching nginx on :{listen_port}..."
nginx -c "$NGINX_CONF"

# If nginx exits, kill children
trap "kill $HOME_PID $FRONTEND_PID 2>/dev/null" EXIT
wait
"""


def detect_frontend_cmd(project_root: Path) -> str:
    """Auto-detect the frontend start command from render.yaml or package.json."""
    # Check render.yaml
    render_yaml = project_root / "render.yaml"
    if render_yaml.exists():
        text = render_yaml.read_text()
        for line in text.split("\n"):
            if "startCommand:" in line:
                cmd = line.split("startCommand:")[1].strip()
                # Remove any home_server parts we may have added
                if "home_server" in cmd:
                    parts = cmd.split("&")
                    for p in parts:
                        if "home_server" not in p and p.strip():
                            return p.strip()
                return cmd

    # Check package.json (Node)
    pkg = project_root / "package.json"
    if pkg.exists():
        import json
        data = json.loads(pkg.read_text())
        start = data.get("scripts", {}).get("start", "")
        if start:
            return start

    # Check for server.py (Python)
    if (project_root / "server.py").exists():
        return "python3 -m uvicorn server:app --host 0.0.0.0 --port $PORT"

    return "echo 'No frontend detected'"


def main():
    parser = argparse.ArgumentParser(description="Setup reverse proxy for mind-mcp")
    parser.add_argument("--port", type=int, default=int(os.environ.get("PORT", 10000)))
    parser.add_argument("--frontend-port", type=int, default=10001)
    parser.add_argument("--backend-port", type=int, default=8765)
    parser.add_argument("--project-root", type=str, default=str(PROJECT_ROOT.parent))
    args = parser.parse_args()

    project = Path(args.project_root)
    runtime_dir = project / ".mind" / "runtime"
    runtime_dir.mkdir(parents=True, exist_ok=True)

    # Generate nginx.conf
    conf = generate_nginx_conf(args.port, args.frontend_port, args.backend_port)
    conf_path = runtime_dir / "nginx.conf"
    conf_path.write_text(conf)
    print(f"  Generated {conf_path}")

    # Generate start.sh
    frontend_cmd = detect_frontend_cmd(project)
    script = generate_start_script(frontend_cmd, args.port, args.frontend_port, args.backend_port)
    script_path = runtime_dir / "start.sh"
    script_path.write_text(script)
    os.chmod(script_path, os.stat(script_path).st_mode | stat.S_IEXEC)
    print(f"  Generated {script_path}")
    print(f"  Frontend: {frontend_cmd}")
    print(f"  Routing: :{args.port} → nginx → home_server:{args.backend_port} + frontend:{args.frontend_port}")


if __name__ == "__main__":
    main()
